module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#cde5ff",
        primary: "#ffb690",
        "outline-variant": "#584237",
        "on-tertiary-fixed": "#001d32",
        "on-surface-variant": "#e0c0b1",
        "on-error-container": "#ffdad6",
        tertiary: "#93ccff",
        "inverse-on-surface": "#2d3137",
        "on-background": "#dfe2eb",
        "on-primary-fixed-variant": "#783200",
        "error-container": "#93000a",
        "tertiary-container": "#00a2f4",
        secondary: "#bcc7de",
        "inverse-primary": "#9d4300",
        "secondary-fixed": "#d8e3fb",
        "inverse-surface": "#dfe2eb",
        "primary-container": "#f97316",
        "on-tertiary": "#003351",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-tint": "#ffb690",
        "primary-fixed": "#ffdbca",
        "on-error": "#690005",
        "on-secondary-container": "#aeb9d0",
        "tertiary-fixed-dim": "#93ccff",
        "on-secondary-fixed": "#111c2d",
        "on-tertiary-container": "#003554",
        "on-primary": "#552100",
        "surface-dim": "#10141a",
        "secondary-fixed-dim": "#bcc7de",
        "on-surface": "#dfe2eb",
        "on-primary-container": "#582200",
        "surface-container-low": "#181c22",
        "primary-fixed-dim": "#ffb690",
        "surface-container-lowest": "#0a0e14",
        error: "#ffb4ab",
        "surface-variant": "#31353c",
        "on-secondary": "#263143",
        "on-tertiary-fixed-variant": "#004b74",
        background: "#10141a",
        "surface-container-highest": "#31353c",
        "surface-container-high": "#262a31",
        "on-primary-fixed": "#341100",
        "surface-bright": "#353940",
        "surface-container": "#1c2026",
        surface: "#10141a",
        "secondary-container": "#3e495d",
        outline: "#a78b7d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1rem",
        "sidebar-width": "260px",
        "toolbar-height": "48px",
        "container-padding": "1.5rem",
        base: "4px",
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "code-sm": ["JetBrains Mono"],
        "label-caps": ["Inter"],
        "headline-md": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "body-sm": ["Inter"],
      },
      fontSize: {
        "display-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-caps": [
          "11px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "code-md": ["13px", { lineHeight: "20px", fontWeight: "450" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
